# Generated by Django 4.2.4 on 2023-08-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_message_count_alter_message_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
